---
- hosts: localhost
  connection: local
  vars:
    ssh_key: nginx
    num_nodes: 2
    security_group_name: nginx
    template: Linux Ubuntu 16.04 LTS 64-bit
    template_filter: featured
    instance_type: Tiny
    zone: ch-gva-2

  roles:
    - common
    - infra
