---
- hosts: localhost
  connection: local
  vars:
    ssh_key: nginx
    num_nodes: 2
    security_group_name: nginx
    template: Linux Ubuntu 14.04 LTS 64-bit 10G Disk (2016-10-20-85bb6c)
    instance_type: Tiny
    zone: ch-gva-2

  roles:
    - common
    - infra
