---
- hosts: localhost
  connection: local
  vars:
    ssh_key: nginx
    num_nodes: 2
    security_group_name: nginx
    template: Linux Ubuntu 14.04 LTS 64-bit 10G Disk (2015-04-22-c2595b)
    instance_type: Tiny

  roles:
    - common
    - infra
